<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Anndy-PC" ignored="0" name="Default test" tests="1" failures="1" timestamp="06 八月 2019 10:09:44 GMT" time="82.108" errors="0">
  <testcase name="loginCase" time="62.568" classname="cn.AnndyTsal.PO.PO_simplify.Case.HomeTestCase1">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
at message : 预期为空 实际不为空 expected [true] but found [false] in method : .loginCase(HomeTestCase1:39)
at cn.AnndyTsal.PO.PO_simplify.Case.HomeTestCase1.loginCase(HomeTestCase1.java:39)
]]>
    </failure>
  </testcase> <!-- loginCase -->
</testsuite> <!-- Default test -->
