<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Anndy-PC" ignored="0" name="Test" tests="1" failures="1" timestamp="08 八月 2019 03:38:17 GMT" time="82.471" errors="0">
  <testcase name="loginCase" time="62.845" classname="cn.AnndyTsal.PO.PO_simplify.Case.HomeTestCase1">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
at message : 预期为空 实际不为空 expected [true] but found [false] in method : .loginCase(HomeTestCase1:53)
at cn.AnndyTsal.PO.PO_simplify.Case.HomeTestCase1.loginCase(HomeTestCase1.java:53)
]]>
    </failure>
  </testcase> <!-- loginCase -->
</testsuite> <!-- Test -->
